### ISSUE TITLE
bower install <package>#<preset>/<version> causes error

### ISSUE THREAD

**Issue by cheezist** [sonatype/bower-nexus3-resolver#10]
Using bower-nexus3-resolver and installing packages such ckeditor with the `#<preset>/<version>` syntax causes an error in bower due (seemingly) to an incorrect resolved URL.

To reproduce, use CKeditor bower example shown here: http://docs.ckeditor.com/#!/guide/dev_package_managers

**D:\project\bower install ckeditor#full/4.5.6**
bower ckeditor#full/4.5.6   not-cached nexus+http://nexus-server/nexus/repository/bower-all/ckeditor#full/4.5.6
bower ckeditor#full/4.5.6      resolve nexus+http://nexus-server/nexus/repository/bower-all/ckeditor#full/4.5.6
bower ckeditor#full/4.5.6        error http://nexus-server/nexus/repository/bower-all/ckeditor/full/4.5.6/package.tar.gz (HTTP 404)

**Stack trace:**
Error: http://nexus-server/nexus/repository/bower-all/ckeditor/full/4.5.6/package.tar.gz (HTTP 404)
    at Request.<anonymous> (C:\Users\me\AppData\Roaming\npm\node_modules\bower-nexus3-resolver\src\index.js:190:24)
    at emitOne (events.js:90:13)
    at Request.emit (events.js:182:7)
    at Request.onRequestResponse (C:\Users\me\AppData\Roaming\npm\node_modules\bower-nexus3-resolver\node_modules\request\request.js:951:10)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:458:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
    at Socket.socketOnData (_http_client.js:348:20)
    at emitOne (events.js:90:13)

**Console trace:**
Error
    at StandardRenderer.error (C:\Users\me\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:81:37)
    at Logger.<anonymous> (C:\Users\me\AppData\Roaming\npm\node_modules\bower\lib\bin\bower.js:110:26)
    at emitOne (events.js:90:13)
    at Logger.emit (events.js:182:7)
    at Logger.emit (C:\Users\me\AppData\Roaming\npm\node_modules\bower\lib\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\me\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:48:20
    at _rejected (C:\Users\me\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:844:24)
    at C:\Users\me\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:870:30
    at Promise.when (C:\Users\me\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\me\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:788:41)
System info:
Bower version: 1.8.0
Node version: 5.8.0
OS: Windows_NT 6.1.7601 x64

**Comment by cheezist** [comment]
After some more research, this may be due to the ckeditor repository. The ckeditor repository doesn't conform to [SemVer](http://semver.org/) convention which might be why this doesn't work with bower-nexus3-resolver.  

Using **bower install ckeditor#full/4.5.6** without a repository works as expected:
D:\Project>bower install ckeditor#full/4.5.6
bower ckeditor#full/4.5.6       cached https://github.com/ckeditor/ckeditor-releases.git#full/4.5.6
bower ckeditor#full/4.5.6     validate full/4.5.6 against https://github.com/ckeditor/ckeditor-releases.git#full/4.5.6

Is there maybe a workaround for using this with a Nexus repository?

**Comment by joedragons** [comment]
@cheezist There is not a workaround I am aware of (besides "obviously" using bower install ckeditor to give the latest "valid" version).  Since we seem to concur this is an issue with their versioning, you might get a better response posting an improvement suggestion on https://issues.sonatype.org/projects/NEXUS.  Then anyone who agrees can vote up your thought.

**Comment by fjmilens3** [comment]
@joedragons and @cheezist, I looked at this briefly before heading out on vacation. 

The actual failure here has to do with Nexus 3's URL routing getting confused by the incoming request and not being able to match it with any of the matchers. Nexus 3 receives a request containing `ckeditor/full/4.5.6/package.tar.gz` but it's trying to match that against `{package:.+}/{version:.+}/package.tar.gz` and the additional forward slash is throwing it off. Depending on what we can do with the routing we may be able to hack something together for this.

The bigger issue is that it's not a valid semantic version, and we've historically not worried about supporting those because the Bower code that uses our pluggable resolver filters all returned versions and throws out invalid ones. This might work as a special case for that, since the requested version is not a valid range and that entire step is skipped, but in the general case, we're not able to support things unless they are valid semantic versions. (This is also where some of the confusion often creeps in with Git tags vs actual semantic versions and the different code paths that come from that.)

**Comment by cheezist** [comment]
@fjmilens3 thanks for looking at it. At this point I think this is a non-issue (and can be closed as such) because of the invalid semantic version of the ckeditor configurations.
