### ISSUE TITLE
v1.0.3: tar.Extract is not a function

### ISSUE THREAD

**Issue by inka** [sonatype/bower-nexus3-resolver#23]
with the latest version we got trouble in our CI and seeing this error message:

08:30:44  [37m[exec] bower jquery#~2.1.1         error tar.Extract is not a function[m

Probably the method signature of tar has changed due to the upgrade 
"tar": "~2.2.1"  => "~4.4.8"

Easiest workaround to fix this fast would be to rollback that and fix it to 2.2.1 again.

**Comment by slavede** [comment]
I also have same issue. When I downgrade back to 1.0.2 it goes away. It's not necessary related with jquery as you have, I got it for angular-ui-select...

```
[ERROR] bower angular-ui-select#25c06c89175293a93b8b4d7c20da8541df4bf4ef            error tar.Extract is not a function
[ERROR] 
[ERROR] Stack trace:
[ERROR] TypeError: tar.Extract is not a function
[ERROR]     at /var/lib/jenkins/jobs/project/workspace/node_modules/bower-nexus3-resolver/src/index.js:255:29
[ERROR]     at Function.promise (/var/lib/jenkins/jobs/project/workspace/node_modules/bower-nexus3-resolver/node_modules/q/q.js:702:9)
[ERROR]     at Object._extractTarGz (/var/lib/jenkins/jobs/project/workspace/node_modules/bower-nexus3-resolver/src/index.js:241:16)
[ERROR]     at /var/lib/jenkins/jobs/project/workspace/node_modules/bower-nexus3-resolver/src/index.js:57:25
[ERROR]     at _fulfilled (/var/lib/jenkins/jobs/project/workspace/node_modules/bower-nexus3-resolver/node_modules/q/q.js:854:54)
[ERROR]     at self.promiseDispatch.done (/var/lib/jenkins/jobs/project/workspace/node_modules/bower-nexus3-resolver/node_modules/q/q.js:883:30)
[ERROR]     at Promise.promise.promiseDispatch (/var/lib/jenkins/jobs/project/workspace/node_modules/bower-nexus3-resolver/node_modules/q/q.js:816:13)
[ERROR]     at /var/lib/jenkins/jobs/project/workspace/node_modules/bower-nexus3-resolver/node_modules/q/q.js:624:44
[ERROR]     at runSingle (/var/lib/jenkins/jobs/project/workspace/node_modules/bower-nexus3-resolver/node_modules/q/q.js:137:13)
[ERROR]     at flush (/var/lib/jenkins/jobs/project/workspace/node_modules/bower-nexus3-resolver/node_modules/q/q.js:125:13)
```

**Comment by tidou44** [comment]
The same. downgrading to 1.0.2

**Comment by joedragons** [comment]
Created https://github.com/sonatype/bower-nexus3-resolver/pull/26 to fix this.  Going to merge now.
